## Basic Configuration
baseurl = "https://ymedlop.es"
theme = "hugo-uno"
languageCode = "es-ES"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
title = "Yeray Medina López"
author = "Yeray Medina López"
copyright = ""

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Yeray"
  github = "ymedlop"
  twitter = "ymedlop"
  linkedin = "ymedlop"
  cover = "/img/background-cover.jpg"
  logo = "/img/avatar.jpg"
  description = "Jack of all trades"
  cv = "/about"